$(document).ready(function(){$.ajaxSetup({cache:false});});var piano_settings;userData=current_user['current_user'].data;var userProfile={get:function(token){let uid=userData.ID;if(!uid){console.log('sss');return;}
$.getJSON('/wp-content/plugins/indeed-membership-pro/apigate.php?ihch=35IfuPtnzqBaT3W5iDyXmsxBjohR5Z&action=user_get_details&uid='+uid,(data)=>{let check=this.checkLevel(uid);if(check){piano_settings=JSON.parse(decodeHTMLEntities(data.response.piano_settings));this.applyOption(piano_settings);}
return piano_settings;})
return piano_settings;},set:function(token){},applyOption:function(piano_settings){let assist=piano_settings.key_assist;let bgcolor=piano_settings.bg_color;let bgtheme=piano_settings.bg_theme;let samples=piano_settings.samples;let sustain=piano_settings.sustain;setPianoOption(assist,bgcolor,bgtheme,samples,sustain);},saveOption:function(){let user_level;let userid=parseInt(current_user.current_user.ID);if(!current_user.current_user['roles'].includes("administrator")&&userid>0){user_level=5;}else if(current_user.current_user['roles'].includes("administrator")&&userid>0){user_level=6;}else if(userid==0){user_level=0;}
if(!user_level||user_level<1){return};let rating=user_meta.user_meta.pianist_rating;if(!rating){rating=1000;}else{rating=parseInt(user_meta.user_meta.pianist_rating[0]);}
let hist;if(user_meta.user_meta.play_history){hist=JSON.parse(decodeHTMLEntities(user_meta.user_meta.play_history));}else{hist="";}
let badges;if(user_meta.user_meta.user_badges&&user_meta.user_meta.user_badges[0].length!=0){badges=JSON.parse(decodeHTMLEntities(user_meta.user_meta.user_badges));}else{badges=JSON.parse('{"g":"0", "s":"0","b":"0"}');}
let settings=user_meta['user_meta'].piano_settings;if(!settings||settings.length<5){settings='{"bg_color":"#ffffff","bg_theme":"AUTUMN","samples":"UPRIGHT PIANO"}'}
settings=JSON.parse(settings);settings.key_assist=keyAssist;settings.bg_color=colorPicker.color.hexString
settings.bg_theme=$('select[name=theme]').val()
settings.samples=$('#piano-type').val();settings.sustain=sustValue;let new_settings=JSON.stringify(settings);let premCheck=this.checkLevel();console.log(premCheck);$.ajax({url:"/wp-admin/admin-ajax.php",type:"POST",data:"action=custom_update_usermeta&pianist_rating="+JSON.stringify(rating)+"&play_history="+JSON.stringify(hist)+"&piano_settings="+JSON.stringify(settings)+"&user_badges="+JSON.stringify(badges),success:function(dat){var data=JSON.parse(dat.toString());if(premCheck){showSaveMessage('Settings have been saved!');}else{$('.save__upgrade').addClass('active');}
$('.save__upgrade .close').click(function(){$('.save__upgrade').removeClass('active');})},error:function(){console.log('Something went wrong');showSaveMessage('Oops...Something went wrong!');}});},checkLevel:function(id){let user_level;let userid=parseInt(current_user.current_user.ID);let levelArr;if(!current_user.current_user['roles'].includes("administrator")&&userid>0){user_level=5;}else if(current_user.current_user['roles'].includes("administrator")&&userid>0){user_level=6;}else if(userid==0){user_level=0;}
if(!user_level||user_level<=4){return false;}else{return true;}}};function showSaveMessage(message){$('.record__timer').addClass('active');$('.record__timer span').html(message).css({'display':'block','animation':'save 4s 0s forwards'});setTimeout(function(){$('.record__timer span').html('').css({'display':'none'});$('.record__timer').removeClass('active upgrade');},4000);}
console.log('applying piano options');function setPianoOption(assist,bgcolor,bgtheme,samples,sustain){if(assist=='assist-notes'){$(this).addClass('assist-notes').addClass('active').removeClass('assist-keys');$(this).attr('value','assist-notes')
$('.assikeys').css({'opacity':'0','transition':'.0s'});$('.assinotes').css({'opacity':'1','transition':'.3s'});$('.assist-btn').addClass('active').addClass('assist-notes');}else if(assist=='assist-keys'){$(this).addClass('assist-keys').addClass('active').removeClass('assist-notes');$(this).attr('value','assist-keys')
$('.assinotes').css({'opacity':'0','transition':'.0s'});$('.assikeys').css({'opacity':'1','transition':'.3s'});$('.assist-btn').addClass('active').addClass('assist-keys');;}else if(assist instanceof Object){Object.keys(assist).forEach((x)=>{keyAssist[x]=assist[x];handleAssist(x,true);})}else{$(this).removeClass('active').removeClass('assist-notes').removeClass('assist-keys');$(this).attr('value','none')
$('.assikeys').css({'opacity':'0','transition':'.3s'});$('.assinotes').css({'opacity':'0','transition':'.3s'});}
$('.type__custom li:contains('+bgtheme+')').trigger('click');colorPicker.color.set(bgcolor);$(".theme select[name='theme']").val(bgtheme).trigger('change');if(window.location.href.indexOf('instr=')===-1){$('.type__custom li[value="'+samples+'"]').trigger('click');$('#piano-type').val(samples).trigger('change');}
if(sustain){sustValue=sustain;$('#sustain_val').html(sustValue);if(sustain==0){$('.sustain input:not(.assist_input_inp)').prop('checked',true);$('.sustain__sign.increment').css({'opacity':'0.3'});$('.sustain__sign.decrement').css({'opacity':'1'});}else if(sustain==-10){$('.sustain input:not(.assist_input_inp)').prop('checked',false);$('.sustain__sign.decrement').css({'opacity':'0.3'});$('.sustain__sign.increment').css({'opacity':'1'});}else{$('.sustain input:not(.assist_input_inp)').prop('checked',true);$('.sustain__sign.decrement').css({'opacity':'1'});$('.sustain__sign.increment').css({'opacity':'1'});}}}